name: Build & Publish Release APK

on:
  push:
    tags:
      - '*'

jobs:
  Gradle:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build Release APK
        run: .\gradlew assembleRelease
      - name: Publish APK
        uses: peaceiris/actions-gradle@v2
        with:
          tasks: publish
          args: --info --stacktrace
        env:
          GITHUB_TOKEN: ${{ secrets.FILEMANAGER_TOKEN }}
